// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"
)

type Calendario struct {
	Fecha         time.Time `json:"fecha"`
	Hora          time.Time `json:"hora"`
	TratamientoID int64     `json:"tratamiento_id"`
	ClienteID     int64     `json:"cliente_id"`
}

type Cliente struct {
	ID          int64  `json:"id"`
	Nombre      string `json:"nombre"`
	Apellido    string `json:"apellido"`
	Deuda       string `json:"deuda"`
	NroTelefono int32  `json:"nro_telefono"`
}

type Tratamiento struct {
	ID               int64  `json:"id"`
	Nombre           string `json:"nombre"`
	DescripcionCorta string `json:"descripcion_corta"`
	Costo            int32  `json:"costo"`
}

type Voucher struct {
	IDVoucher     int64 `json:"id_voucher"`
	RegaladorID   int64 `json:"regalador_id"`
	TratamientoID int64 `json:"tratamiento_id"`
	ClienteID     int64 `json:"cliente_id"`
}
