// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
	"time"
)

const createCalendar = `-- name: CreateCalendar :one
INSERT INTO calendario (fecha, hora, tratamiento_id, cliente_id)
VALUES ($1, $2, $3, $4)
RETURNING fecha, hora, tratamiento_id, cliente_id
`

type CreateCalendarParams struct {
	Fecha         time.Time `json:"fecha"`
	Hora          time.Time `json:"hora"`
	TratamientoID int64     `json:"tratamiento_id"`
	ClienteID     int64     `json:"cliente_id"`
}

func (q *Queries) CreateCalendar(ctx context.Context, arg CreateCalendarParams) (Calendario, error) {
	row := q.db.QueryRowContext(ctx, createCalendar,
		arg.Fecha,
		arg.Hora,
		arg.TratamientoID,
		arg.ClienteID,
	)
	var i Calendario
	err := row.Scan(
		&i.Fecha,
		&i.Hora,
		&i.TratamientoID,
		&i.ClienteID,
	)
	return i, err
}

const createTreatment = `-- name: CreateTreatment :one
INSERT INTO tratamiento (nombre, descripcion_corta, costo)
VALUES ($1, $2, $3)
RETURNING id, nombre, descripcion_corta, costo
`

type CreateTreatmentParams struct {
	Nombre           string `json:"nombre"`
	DescripcionCorta string `json:"descripcion_corta"`
	Costo            int32  `json:"costo"`
}

func (q *Queries) CreateTreatment(ctx context.Context, arg CreateTreatmentParams) (Tratamiento, error) {
	row := q.db.QueryRowContext(ctx, createTreatment, arg.Nombre, arg.DescripcionCorta, arg.Costo)
	var i Tratamiento
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.DescripcionCorta,
		&i.Costo,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO cliente (nombre, apellido, deuda, nro_telefono)
VALUES ($1, $2, $3, $4)
RETURNING id, nombre, apellido, deuda, nro_telefono
`

type CreateUserParams struct {
	Nombre      string `json:"nombre"`
	Apellido    string `json:"apellido"`
	Deuda       string `json:"deuda"`
	NroTelefono int32  `json:"nro_telefono"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (Cliente, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Nombre,
		arg.Apellido,
		arg.Deuda,
		arg.NroTelefono,
	)
	var i Cliente
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Apellido,
		&i.Deuda,
		&i.NroTelefono,
	)
	return i, err
}

const createVoucher = `-- name: CreateVoucher :one
INSERT INTO voucher (regalador_id, tratamiento_id, cliente_id)
VALUES ($1, $2, $3)
RETURNING id_voucher, regalador_id, tratamiento_id, cliente_id
`

type CreateVoucherParams struct {
	RegaladorID   int64 `json:"regalador_id"`
	TratamientoID int64 `json:"tratamiento_id"`
	ClienteID     int64 `json:"cliente_id"`
}

func (q *Queries) CreateVoucher(ctx context.Context, arg CreateVoucherParams) (Voucher, error) {
	row := q.db.QueryRowContext(ctx, createVoucher, arg.RegaladorID, arg.TratamientoID, arg.ClienteID)
	var i Voucher
	err := row.Scan(
		&i.IDVoucher,
		&i.RegaladorID,
		&i.TratamientoID,
		&i.ClienteID,
	)
	return i, err
}

const deleteCalendar = `-- name: DeleteCalendar :exec
DELETE FROM calendario
WHERE fecha = $1 AND hora = $2
`

type DeleteCalendarParams struct {
	Fecha time.Time `json:"fecha"`
	Hora  time.Time `json:"hora"`
}

func (q *Queries) DeleteCalendar(ctx context.Context, arg DeleteCalendarParams) error {
	_, err := q.db.ExecContext(ctx, deleteCalendar, arg.Fecha, arg.Hora)
	return err
}

const deleteTreatment = `-- name: DeleteTreatment :exec
DELETE FROM tratamiento
WHERE id = $1
`

func (q *Queries) DeleteTreatment(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTreatment, id)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM cliente
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const deleteVoucher = `-- name: DeleteVoucher :exec
DELETE FROM voucher
WHERE id_voucher = $1
`

func (q *Queries) DeleteVoucher(ctx context.Context, idVoucher int64) error {
	_, err := q.db.ExecContext(ctx, deleteVoucher, idVoucher)
	return err
}

const getCalendar = `-- name: GetCalendar :one
SELECT fecha, hora, tratamiento_id, cliente_id
FROM calendario 
WHERE fecha = $1 AND hora = $2
`

type GetCalendarParams struct {
	Fecha time.Time `json:"fecha"`
	Hora  time.Time `json:"hora"`
}

// TABLA CALENDARIO
func (q *Queries) GetCalendar(ctx context.Context, arg GetCalendarParams) (Calendario, error) {
	row := q.db.QueryRowContext(ctx, getCalendar, arg.Fecha, arg.Hora)
	var i Calendario
	err := row.Scan(
		&i.Fecha,
		&i.Hora,
		&i.TratamientoID,
		&i.ClienteID,
	)
	return i, err
}

const getTreatment = `-- name: GetTreatment :one
SELECT id, nombre, descripcion_corta, costo
FROM tratamiento
WHERE id = $1
`

// TABLA TRATAMIENTO
func (q *Queries) GetTreatment(ctx context.Context, id int64) (Tratamiento, error) {
	row := q.db.QueryRowContext(ctx, getTreatment, id)
	var i Tratamiento
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.DescripcionCorta,
		&i.Costo,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, nombre, apellido, deuda, nro_telefono
FROM cliente
WHERE id = $1
`

// TABLA CLIENTE
func (q *Queries) GetUser(ctx context.Context, id int64) (Cliente, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i Cliente
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Apellido,
		&i.Deuda,
		&i.NroTelefono,
	)
	return i, err
}

const getVoucher = `-- name: GetVoucher :one
SELECT id_voucher, regalador_id, tratamiento_id, cliente_id
FROM voucher
WHERE id_voucher = $1
`

// TABLA VOUCHER
func (q *Queries) GetVoucher(ctx context.Context, idVoucher int64) (Voucher, error) {
	row := q.db.QueryRowContext(ctx, getVoucher, idVoucher)
	var i Voucher
	err := row.Scan(
		&i.IDVoucher,
		&i.RegaladorID,
		&i.TratamientoID,
		&i.ClienteID,
	)
	return i, err
}

const listCalendar = `-- name: ListCalendar :many
SELECT fecha, hora, tratamiento_id, cliente_id
FROM calendario
ORDER BY fecha, hora
`

func (q *Queries) ListCalendar(ctx context.Context) ([]Calendario, error) {
	rows, err := q.db.QueryContext(ctx, listCalendar)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Calendario
	for rows.Next() {
		var i Calendario
		if err := rows.Scan(
			&i.Fecha,
			&i.Hora,
			&i.TratamientoID,
			&i.ClienteID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTreatments = `-- name: ListTreatments :many
SELECT id, nombre, descripcion_corta, costo
FROM tratamiento
ORDER BY id
`

func (q *Queries) ListTreatments(ctx context.Context) ([]Tratamiento, error) {
	rows, err := q.db.QueryContext(ctx, listTreatments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tratamiento
	for rows.Next() {
		var i Tratamiento
		if err := rows.Scan(
			&i.ID,
			&i.Nombre,
			&i.DescripcionCorta,
			&i.Costo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, nombre, apellido, deuda, nro_telefono
FROM cliente
ORDER BY id
`

func (q *Queries) ListUsers(ctx context.Context) ([]Cliente, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Cliente
	for rows.Next() {
		var i Cliente
		if err := rows.Scan(
			&i.ID,
			&i.Nombre,
			&i.Apellido,
			&i.Deuda,
			&i.NroTelefono,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCalendar = `-- name: UpdateCalendar :exec
UPDATE calendario
SET tratamiento_id = $3, cliente_id = $4
WHERE fecha = $1 AND hora = $2
`

type UpdateCalendarParams struct {
	Fecha         time.Time `json:"fecha"`
	Hora          time.Time `json:"hora"`
	TratamientoID int64     `json:"tratamiento_id"`
	ClienteID     int64     `json:"cliente_id"`
}

func (q *Queries) UpdateCalendar(ctx context.Context, arg UpdateCalendarParams) error {
	_, err := q.db.ExecContext(ctx, updateCalendar,
		arg.Fecha,
		arg.Hora,
		arg.TratamientoID,
		arg.ClienteID,
	)
	return err
}

const updateTreatment = `-- name: UpdateTreatment :exec
UPDATE tratamiento
SET nombre = $2, descripcion_corta = $3, costo = $4
WHERE id = $1
`

type UpdateTreatmentParams struct {
	ID               int64  `json:"id"`
	Nombre           string `json:"nombre"`
	DescripcionCorta string `json:"descripcion_corta"`
	Costo            int32  `json:"costo"`
}

func (q *Queries) UpdateTreatment(ctx context.Context, arg UpdateTreatmentParams) error {
	_, err := q.db.ExecContext(ctx, updateTreatment,
		arg.ID,
		arg.Nombre,
		arg.DescripcionCorta,
		arg.Costo,
	)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE cliente
SET nombre = $2, apellido = $3, deuda = $4, nro_telefono = $5
WHERE id = $1
`

type UpdateUserParams struct {
	ID          int64  `json:"id"`
	Nombre      string `json:"nombre"`
	Apellido    string `json:"apellido"`
	Deuda       string `json:"deuda"`
	NroTelefono int32  `json:"nro_telefono"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser,
		arg.ID,
		arg.Nombre,
		arg.Apellido,
		arg.Deuda,
		arg.NroTelefono,
	)
	return err
}

const updateVoucher = `-- name: UpdateVoucher :exec
UPDATE voucher
SET regalador_id = $2, tratamiento_id = $3, cliente_id = $4
WHERE id_voucher = $1
`

type UpdateVoucherParams struct {
	IDVoucher     int64 `json:"id_voucher"`
	RegaladorID   int64 `json:"regalador_id"`
	TratamientoID int64 `json:"tratamiento_id"`
	ClienteID     int64 `json:"cliente_id"`
}

func (q *Queries) UpdateVoucher(ctx context.Context, arg UpdateVoucherParams) error {
	_, err := q.db.ExecContext(ctx, updateVoucher,
		arg.IDVoucher,
		arg.RegaladorID,
		arg.TratamientoID,
		arg.ClienteID,
	)
	return err
}
